### PR TITLE
Utk v2

### PR DESCRIPTION
**Pull request by BDoignies**
Big changes. 

UTK v2 is an entire rewrite of UTK. File tree, samplers, metrics and all have been changed ! This was not fully tested !

For better or worse :clown_face: !

### CODE REVIEW

**Comment by dcoeurjo** [comment]
🎉🎉

**Comment by BDoignies** [comment]
If you considering merging the PR, I think it would be a good idea to tag previous version.

**Comment by dcoeurjo** [comment]
Done for the tag

**Comment by dcoeurjo** [comment]
Ok looks perfectly fine to me.. Maybe issues will arise after the merge but looks good.
many thanks @BDoignies !!
🎉

**Comment by dcoeurjo** [comment]
Before I merge, could you please update the changelog thing with the v1 changelog mkdocs page?

**Comment by BDoignies** [comment]
@dcoeurjo Done (+ FFT for free Basic algorithm is horribly slow ...)

**Comment by dcoeurjo** [comment]
Maybe doc update as well ?

**Comment by BDoignies** [comment]
Not sure to understand. The documentation was updated with the changelog (as a copy of the changelog.md in the root directory). 

As for FFTW this is a technical detail, not sure that a flag in the metric computation is really a good thing. 'Direct computation' of DFT is indeed a regression.

So far, there is a CMake option (UTK_USE_FFTW) that disables FFTW usage. By default, it is set to true and fallback to 'direct computation' if the library is not found.

**Comment by dcoeurjo** [comment]
I've updated the spectrum doc.
Just a question, we have `doc` (md sources) `docs` (generated static pages) and `sources-doc` (empty). What is the later one?

I wouldn't mind if we move files from doc to sources-doc to clarify doc/docs. What do you think?

**Comment by BDoignies** [comment]
There is no folder named 'sources-doc' on my side. This is confirmed by the source fork 'https://github.com/BDoignies/utk/tree/utk-v2'. At least, not in the root directory... 

The only thing I can do is to rename the 'doc' folder to 'source/doc'...

**Comment by dcoeurjo** [comment]
let's see that later. merging. 
GG 🥳

**Pull request merged**
