### PR TITLE
Add an option to load external Sobol init table

### PR DESCRIPTION
**Pull request by dcoeurjo**

### CODE REVIEW

**Comment by dcoeurjo** [comment]
Could you please check this, @BDoignies ?

**Comment by BDoignies** [comment]
Sorry for the delay,

The name of the new option is a bit long for me. Otherwise LGTM. 

Bastien

**Comment by dcoeurjo** [comment]
just `--table` ?

**Comment by dcoeurjo** [comment]
Is this PR mergable ?

**Comment by dcoeurjo** [comment]
ping @BDoignies

**Pull request merged**
