### PR TITLE
Updating scramblers doc

### PR DESCRIPTION
**Pull request by dcoeurjo**

### CODE REVIEW

**Comment by dcoeurjo** [comment]
WIP

**Comment by dcoeurjo** [comment]
The description of Owen's and OwenTree could be clarified (by describing their parameters for instance). Does OwenTree consist in scrambling with a user-specified tree ?
For the regular one, the `max_depth` param could be described.

**Comment by BDoignies** [comment]
* Owen is regular Owen's scrambling. The tree are not stored, hence a depth of 32 do not have a noticeable memory overhead. 
* OwenTree is also Owen's scrambling, but the trees are PARTIALLY STORED. The key idea is that user may only specified the first few bits of the underlying tree. The rest (until max_depth) is randomly sampled (without any storage of tree). A depth 32 is still possible and the user may only provide the first 4 levels of the tree if he desires.  

I will rephrase the elements so that everything is clearer.

**Comment by dcoeurjo** [comment]
Great. Thx

**Comment by BDoignies** [comment]
Is it clearer now :) ?

**Comment by dcoeurjo** [comment]
ok great
I've just fixed some mathjax stuff
merging...

**Pull request merged**
